//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartManagement.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Stock_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public int Stock_Quantity { get; set; }
        public int Stock_RetailPrice { get; set; }
        public decimal Stock_TotalPrice { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
