//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartManagement.BOL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        public int Transaction_Id { get; set; }
        public Nullable<int> PaymentType_Id { get; set; }
 
        [Required(ErrorMessage = "*")]
        [Display(Name = "Transaction Date")]
        public System.DateTime Transaction_Date { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Transaction Final Total")]
        public decimal Transaction_FinalTotal { get; set; }
        public Nullable<int> Order_Id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
